export const ROLES = Object.freeze({
  ADMIN: "ADMIN",
  WAREHOUSE_EMPLOYEE: "WAREHOUSE_EMPLOYEE",
  DELIVERY_PARTNER: "DELIVERY_PARTNER",
  CUSTOMER: "CUSTOMER"
});

export const ROLE_LABELS = Object.freeze({
  ADMIN: "Administrator",
  WAREHOUSE_EMPLOYEE: "Warehouse Employee",
  DELIVERY_PARTNER: "Delivery Partner",
  CUSTOMER: "Customer"
});

export const PERMISSIONS = Object.freeze({
  VIEW_DASHBOARD: "VIEW_DASHBOARD",
  CREATE_CONSIGNMENT: "CREATE_CONSIGNMENT",
  UPDATE_CONSIGNMENT: "UPDATE_CONSIGNMENT",
  VIEW_CONSIGNMENTS: "VIEW_CONSIGNMENTS",
  VIEW_TRACKING: "VIEW_TRACKING",
  MANAGE_WAREHOUSES: "MANAGE_WAREHOUSES",
  MANAGE_PARTNERS: "MANAGE_PARTNERS",
  MANAGE_USERS: "MANAGE_USERS",
  RECEIVE_SHIPMENT: "RECEIVE_SHIPMENT",
  DISPATCH_SHIPMENT: "DISPATCH_SHIPMENT",
  ASSIGN_PARTNER: "ASSIGN_PARTNER",
  DELIVERY_OTP: "DELIVERY_OTP",
  CUSTOMER_TRACK: "CUSTOMER_TRACK"
});

export const ROLE_PERMISSIONS = Object.freeze({
  ADMIN: Object.values(PERMISSIONS),
  WAREHOUSE_EMPLOYEE: [
    PERMISSIONS.VIEW_DASHBOARD, PERMISSIONS.CREATE_CONSIGNMENT,
    PERMISSIONS.UPDATE_CONSIGNMENT, PERMISSIONS.VIEW_CONSIGNMENTS,
    PERMISSIONS.VIEW_TRACKING, PERMISSIONS.MANAGE_WAREHOUSES,
    PERMISSIONS.MANAGE_PARTNERS, PERMISSIONS.RECEIVE_SHIPMENT,
    PERMISSIONS.DISPATCH_SHIPMENT, PERMISSIONS.ASSIGN_PARTNER
  ],
  DELIVERY_PARTNER: [
    PERMISSIONS.VIEW_DASHBOARD, PERMISSIONS.VIEW_TRACKING,
    PERMISSIONS.DELIVERY_OTP
  ],
  CUSTOMER: [PERMISSIONS.CUSTOMER_TRACK]
});
